### ISSUE TITLE
Missing "}" in Example Code

### ISSUE THREAD

**Issue by geirman** [bluebill1049/react-simple-animate#24]
On your example site (https://react-simple-animate.herokuapp.com/), you're missing a closing bracket. I'd have submitted a PR, but I wasn't sure where to make that change. 

![image](https://user-images.githubusercontent.com/1640318/32203815-ed837ff2-bda2-11e7-8539-1cd32ba4146d.png)

**Comment by bluebill1049** [comment]
oops thx fix that right away 👍

**Comment by bluebill1049** [comment]
Thanks buddy.

https://github.com/bluebill1049/react-simple-animate/commit/a3232347614ed0b438e65b96f421b3b0de1b45f0

i have fixed and merged the PR. it's in the example folder.
