### ISSUE TITLE
Move react and react-dom from dependencies to peerDependencies

### ISSUE THREAD

**Issue by bogdansoare** [bluebill1049/react-simple-animate#28]
Be specifying react and react-dom as dependencies they are installed also which shouldn't be the case. Please change them to peerDependencies.

**Comment by bluebill1049** [comment]
Thanks! good pick up, i will sort this out over the weekend with react 16 upgrade for the project. many thanks ❤️

**Comment by bogdansoare** [comment]
Cool. Thank you for all the work on this library ❤️

**Comment by bluebill1049** [comment]
Thank you again for your report. This have been resolved now with testing.
