### ISSUE TITLE
AnimateGroup won't start

### ISSUE THREAD

**Issue by vikvikvr** [bluebill1049/react-simple-animate#39]
```javascript
import { Animate, AnimateGroup } from 'react-simple-animate';

let animation = {
         startStyle: {opacity: 0},
         endStyle: {opacity: 1},
         durationSeconds: 1
      }

let arr = [0,1,2,3,4,5,6,7,8,9,10]

...

return <AnimateGroup play>
         {arr.map(el => <Animate sequenceIndex={el} {...animation}>
            <div>{el}</div>
         </Animate>)}
      </AnimateGroup>```

what am I missing?

**Comment by bluebill1049** [comment]
hey @vikvikvr,

you are not miss anything...

https://codesandbox.io/s/llyn05mzoz

it just works with your code, check the code sand box above

cheers
bill

**Comment by vikvikvr** [comment]
Thanks, apparently I was messing too much with Redux  so my state-depending animation would not work. Now I simplified the code a bit and it works like a charm! Awesome library btw 👍

**Comment by bluebill1049** [comment]
thanks @vikvikvr i am glad it works for you ❤️
