### ISSUE TITLE
useAnimateKeyframes to show element when in viewport

### ISSUE THREAD

**Issue by guacamoli** [bluebill1049/react-simple-animate#46]
First off, awesome project -- it's been super useful for me.

**The issue:**
I'm trying to use `useAnimateKeyframes` to show an element when it comes into view. However, unlike `useAnimate` where startStyle is applied as an initial style, the 0% state of the keyframes isn't applied until `play` is actually called. 

Essentially, the behavior ends up being that the element has `opacity: 1` to start, but when it gets scrolled into view (and play() is called), the element flickers for a second as the element initializes to `opacity: 0` and then proceeds to animate properly to `opacity: 1`.

Am I just missing something or using it incorrectly? Please advise.

**Comment by bluebill1049** [comment]
hey @guacamoli,

Mate, you are ahead of the game! my next feature for RSI is going to support `playInViewPort`, so until hit the view start playing the animation. hahaha 

for now, can you do this?

```
// set to true when it's in the view port 
const { inView } = useInViewPort(false);

<AnimateKeyframes
  play
  iterationCount="infinite"
  direction="alternate"
  duration={5}
  playState=`${inView ? 'running' : 'paused'}`
  keyframes={[
    'transform: rotateX(0) rotateY(0) rotateZ(0)',
    'transform: rotateX(360deg) rotateY(360deg) rotateZ(360deg)',
  ]}
>
  <Component />
</AnimateKeyframes>
```

**Comment by guacamoli** [comment]
Hey @bluebill1049, thanks for the quick response. Thats awesome to hear. I'll try out the suggestion. BTW, I've basically combined your animate hook with **react-hook-inview** to create a HOC that does the in viewport animation.

**It works pretty well (in case you wanted any ideas :P):**

```
import React, { Component, useRef } from 'react';
import useInView from 'react-hook-inview';
import { useAnimate } from 'react-simple-animate';

const ANIMATION_STYLES = {
  ...
  'fadeInDown': {
    startStyle: {
      opacity: '0',
      transform: 'translateY(-40%)'
    },
    endStyle: {
      opacity: 1,
      transform: 'translateY(0px)'
    }
  },
  ...
};

export function withViewportAnimation(WrappedComponent) {
  return (props) => {
    const element = useRef();
    const { animationType, durationSeconds, threshold, delaySeconds, ...rest } = props;
    const animationStyles = ANIMATION_STYLES[animationType || 'fadeInDown'];

    const [{style, play}, startAnimation] = useAnimate({
      startStyle: animationStyles.startStyle,
      endStyle: animationStyles.endStyle,
      durationSeconds: durationSeconds || '0.3',
      delaySeconds: delaySeconds
    });

    useInView({
      target: element,
      threshold: threshold || threshold === 0 ? threshold : 0.25,
      onEnter: ([entry]) => startAnimation(true),
      unobserveOnEnter: true
    });

    return <WrappedComponent style={ style } ref={element} {...rest} />;
  }
}

const AnimatedH1 = withViewportAnimation(styled.h1);

<AnimatedH1 animationType="fadeInDown">Heading</AnimatedH1>
```

**Comment by guacamoli** [comment]
Worked! Thanks!

**Comment by bluebill1049** [comment]
nice going to bake `inViewPort` into all the components/hooks for the next feature. 🙏 

ideally just like below

`const { style } = useAnimate({ playInView, start: {opacity: 0 }, end: { opacity: 1 } })`

**Comment by guacamoli** [comment]
That's great! One more question, running into the same issue with using AnimateGroup with AnimateKeyframes. The keyframe 0% state doesn't get applied until the sequence index is ready to animate.

**Comment by bluebill1049** [comment]
hmmm, that's something need a patch. I may change `playState` to `play`, so those probably can go away.

**Comment by bluebill1049** [comment]
ok latest version should work for you https://github.com/bluebill1049/react-simple-animate/releases/tag/3.1.0 let me know how did you :)

**Comment by guacamoli** [comment]
Thanks! Will try it out tonight!

**Comment by guacamoli** [comment]
Hey @bluebill1049, so what is the usage look like now? This was working for me before for the original usecase:

```
const [{style, play}, startAnimation] = useAnimateKeyframes({
      durationSeconds: 1,
      playState:`${inView ? 'running' : 'paused'}`,
      keyframes: animationStyles.keyframes
    });
```

After the upgrade it doesn't. Do I change playstate to play? This doesn't seem to work: 
```
const [{style, play}, startAnimation] = useAnimateKeyframes({
      durationSeconds: 1,
      play: !!inView,
      keyframes: animationStyles.keyframes
    });
```

Or can I start using startAnimation when the element comes into view (like I can do with useAnimate)? The above is for the non-AnimationGroup case.

**Comment by guacamoli** [comment]
I haven't tried the AnimateGroup case yet because my original stopped working after the removal of playState and I'm trying to make that work again with the new code.

**Comment by bluebill1049** [comment]
you are using version 2.

version 3 was released a couple days ago: 
https://github.com/bluebill1049/react-simple-animate/releases/tag/3.0.1

```
const [{style, play}, startAnimation] = useAnimateKeyframes({
      duration: 1,
      play:`${inView ? 'running' : 'paused'}`,
      keyframes: animationStyles.keyframes
    });
```

should fix them, i have removed all the `seconds` in the prop name

**Comment by guacamoli** [comment]
AH, I upgraded to 3.1.1 didn't realize the props changed from my previous version 🤦‍♂

**Comment by guacamoli** [comment]
Updated everything to latest props names -- getting an error now `TypeError: [object Object] is not iterable!`

Few questions:
1. Is this still valid `const [{style, play}, startAnimation] = useAnimateKeyframes(...)`? 
2. I think I'm just a bit confused because I was using the old docs and I think it's out of date now. Can you share an example of a `useAnimateKeyframes` assuming you a variable `inView` that triggers the animation?

😓

**Comment by guacamoli** [comment]
NVM, I see the README has new examples. I was still looking at: https://react-simple-animate.now.sh/hooks

Ok, I think I'm back having the original issue as fixed -- although when I refresh the page I feel that it might be jumpy for a second. Will keep you posted if I continue seeing it.

**Comment by bluebill1049** [comment]
I think `useAnimateGroup` should take care of things, you probably don't need `useAnimate` together. 🙏 version 3 is smaller and faster build with the hook (half the package size 🙏 )

**Comment by guacamoli** [comment]
Thanks for all your help!
