### ISSUE TITLE
Re-render on parent triggers animation

### ISSUE THREAD

**Issue by hthief** [bluebill1049/react-simple-animate#58]
**Describe the bug**
While developing a cross-fade animation component I encountered an issue that occurred on every first render. 
At first, I considered the possibility of SSR not working properly, but when taking a look into the upper component tree I noticed having a couple of unwanted re-renders.
Basically, at the very least while using useAnimateKeyframes hooks, when the parent component re-rendered the animated child comp would also re-render and trigger the animation. 

**To Reproduce**
I'm providing a very barebones example, clicking the trigger re-render button will trigger the behaviour: 
https://codesandbox.io/embed/stupefied-chatterjee-8ecgg

**Expected behavior**
I'm not quite sure but maybe this is the intended behaviour and I should handle the extra renders. Even so, I expected the animation to not play.

**Desktop (please complete the following information):**
 - OS: [osx]
 - Browser [chrome, firefox]

**Comment by bluebill1049** [comment]
hi @hthief,

thanks for the detailed issue report.

you just need this: React.memo to stop unnecessary re-render

`const Placeholder = React.memo(({ fade, ...rest }) => {`

cheers
bill

**Comment by hthief** [comment]
uh-doy, you're right. I tend to overlook where and when to apply memo 😬

thanks!

**Comment by bluebill1049** [comment]
no worries :)
