### ISSUE TITLE
TypeError: useRef$1 is not a function

### ISSUE THREAD

**Issue by JonathanStefanov** [bluebill1049/react-simple-animate#60]
**Description of the bug**
I get that error whenever I put a <Animate> component in my code. I do not get the error then that component is not there.

**Screenshots**
![Error Message](https://i.imgur.com/MGbvhWk.png)
![My Code](https://i.imgur.com/7fdpaK6.png)

**Comment by bluebill1049** [comment]
what's your react version? is your react support hooks? 16.8

**Comment by JonathanStefanov** [comment]
My react version is 16.6.3.
Should I upgrade it to 16.8?

**Comment by JonathanStefanov** [comment]
https://github.com/kesne/with-react-hooks
I've tried to make it support hooks with that but it does not seem to work

**Comment by bluebill1049** [comment]
@JonathanStefanov yeah I think you need to upgrade your React to 16.8
otherwise, you can use the older version 2.x

**Comment by bluebill1049** [comment]
going to close this issue, feel free to reopen if you still have questions around it.
