### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by wdfinch** [bluebill1049/react-simple-animate#77]
On the documentation, specifically for the `<AnimateKeyframes />` component, the following code is presented: 

```
<AnimateKeyframes 
    play 
    delay={1}
    duration={10}
    iterationCount={3}
    direction="alternative"
    keyframes={[
      'transform: translateY(0)',
      'transform: translateY(10px)',
    ]} 
  >
    <YourComponent />
  </AnimateKeyframes>
```

However, `direction="alternative"` is not a valid prop. I believe this should be `alternate`.

https://react-simple-animate.now.sh/animate-keyframes

**Comment by bluebill1049** [comment]
you are right! thanks

**Comment by bluebill1049** [comment]
fixed.
